M48
; DRILL file {KiCad 8.0.2} date 2025-03-07T16:53:27+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-07T16:53:27+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X3.2545Y-2.1244
X3.4455Y-2.1244
T2
X3.2427Y-2.0051
X3.4573Y-2.0051
T3
X1.9Y-2.02
X1.9Y-3.92
X4.72Y-2.02
X4.72Y-3.92
M30
